### ISSUE TITLE
beautify: spacing and eyecandy

### ISSUE THREAD

**Issue by vortex73** [acmpesuecc/ASTViz#3]
For larger Trees its noticibly more compressed at the top of the window. Space out the nodes of the tree in such a way as to make the tree more aesthetic and make use of the window space more.

- [ ] Spacing between nodes and lines.
- [ ] Better colors(*please*)
- [ ] Better Animations

**Comment by Harshinigrandhi2005** [comment]
can you assign this to me @vortex73

**Comment by vortex73** [comment]
!assign @Harshinigrandhi2005 60

**Comment by Harshinigrandhi2005** [comment]
i got assigned somethign else

**Comment by kdb04** [comment]
can i get this assigned?

**Comment by vortex73** [comment]
!assign @kdb04 60

**Comment by kdb04** [comment]
reassign again

**Comment by vortex73** [comment]
!assign @kdb04  60

**Comment by sherlockhome12** [comment]
hey can i get this assigned??

**Comment by sherlockhome12** [comment]
@vortex73
